### ISSUE TITLE
Room/Zone Names not available as objects

### ISSUE THREAD

**Issue by seb2010** [DrozmotiX/ioBroker.tado#202]
Hi,
I am just starting with this adapter migration from ham/tado-platform-plugin. As of now I cannot see the Room/Zone Name-Information anywhere. The Rooms have only the Zone-IDs as sub-objects.
Is it possible to make it configurable, that you either have the room-structure organized by the room-IDs or as an alternative by the room-names?
This would be much easier to navigate for editing in VIS and programming in JS.

**Comment by seb2010** [comment]
the only location I can read the zone-id name resolution is in tado.0.xxxxxx._info.JSON_response.Stage_08_ZonesData

**Comment by HGlab01** [comment]
good morning,
you can try this experimental version which is very much refactored. It is in an early stage and supports all data from the Tado API.
It can be installed by using
DrozmotiX/ioBroker.tado#4d069d77e239cf50d0529fbd7b2d20a35dc7bb76
as URL like this
![image](https://user-images.githubusercontent.com/54232526/114819889-73f95800-9dbe-11eb-98ce-9036c8d9f3cd.png)

In this implementation you have the name twice:
![image](https://user-images.githubusercontent.com/54232526/114820143-d6eaef00-9dbe-11eb-9599-4860d8c8eed7.png)
and
as state tado.X.YYYYYY.Rooms.Z.name

Fingers crossed that this version of the adapter works in your system :-)

**Comment by seb2010** [comment]
I will try it right now. How will the future versions look like? If I now map everything to the experimental version, will this be the future object structure or will I be stuck with this versions since the offical one will still use the current structure?

First impression:
- names are available now
- the sub-structure "MobileDevices" changed to "Mobile_Devices"
thank you very much

**Comment by HGlab01** [comment]
Hi @seb2010!
The main-developer is @DutchmanNL and I am in close collaboration with him.
My target is to switch to the refactored version and it is very cool, that it works fine on your side "out of the box". You did the very fist installation outside my development environment ;-)
If and when to switch to the refactored version has to be further discussed...  But I believe will do pretty soon!

Where did you find "Mobile_Devices"? My path looks like
tado.X.YYYYYY.MobileDevices

**Comment by seb2010** [comment]
it is gone now, was maybe the typing of the prior version.
Found another issue: the Rooms indices for the last Room are mixed up with the heating "room" at index 0. I have a thermostat as zone 8 but values and naming is mixed up with the heating zone 0.

**Comment by HGlab01** [comment]
Hi! Can you please run in debug mode and share the json in 
._info.JSON_response.Stage_09_ZoneStates_data_1 to x

What you mentioned should not happen and based on your explanation I have no idea why this can happen.
Maybe it is solved when you delete all tado states on time because it is something from the prior version?

**Comment by seb2010** [comment]
I have deleted all states prior to the last instance restart. Still the same. And: when I try to set the temperature the adapter crashes:
`

host.ioBroker-pi4 | 2021-04-15 21:42:44.317 | info | instance system.adapter.tado.0 started with pid 16919
-- | -- | -- | --
host.ioBroker-pi4 | 2021-04-15 21:42:14.272 | info | Restart adapter system.adapter.tado.0 because enabled
host.ioBroker-pi4 | 2021-04-15 21:42:14.271 | error | instance system.adapter.tado.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
host.ioBroker-pi4 | 2021-04-15 21:42:14.271 | error | Caught by controller[0]: at processTicksAndRejections (internal/process/task_queues.js:84:21)
host.ioBroker-pi4 | 2021-04-15 21:42:14.271 | error | Caught by controller[0]: at endReadableNT (_stream_readable.js:1241:12)
host.ioBroker-pi4 | 2021-04-15 21:42:14.270 | error | Caught by controller[0]: at IncomingMessage.EventEmitter.emit (domain.js:483:12)
host.ioBroker-pi4 | 2021-04-15 21:42:14.270 | error | Caught by controller[0]: at IncomingMessage.emit (events.js:326:22)
host.ioBroker-pi4 | 2021-04-15 21:42:14.270 | error | Caught by controller[0]: at IncomingMessage.handleStreamEnd (/opt/iobroker/node_modules/axios/lib/adapters/http.js:260:11)
host.ioBroker-pi4 | 2021-04-15 21:42:14.269 | error | Caught by controller[0]: at settle (/opt/iobroker/node_modules/axios/lib/core/settle.js:17:12)
host.ioBroker-pi4 | 2021-04-15 21:42:14.269 | error | Caught by controller[0]: at createError (/opt/iobroker/node_modules/axios/lib/core/createError.js:16:15)
host.ioBroker-pi4 | 2021-04-15 21:42:14.269 | error | Caught by controller[0]: Error: Request failed with status code 422
host.ioBroker-pi4 | 2021-04-15 21:42:14.262 | error | Caught by controller[0]: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected
tado.0 | 2021-04-15 21:42:13.626 | debug | (16750) Polling-Timer cleared.
tado.0 | 2021-04-15 21:42:13.612 | debug | (16750) No suitable Lua script, fallback to keys!: function(doc) { if (doc.type === 'state') emit(doc._id, doc) }
tado.0 | 2021-04-15 21:42:13.609 | warn | (16750) Terminated (UNCAUGHT_EXCEPTION): Without reason
tado.0 | 2021-04-15 21:42:13.608 | debug | (16750) Plugin sentry destroyed
tado.0 | 2021-04-15 21:42:13.607 | info | (16750) terminating
tado.0 | 2021-04-15 21:42:13.606 | info | (16750) cleaned everything up...
tado.0 | 2021-04-15 21:42:13.592 | error | (16750) Request failed with status code 422
tado.0 | 2021-04-15 21:42:13.591 | error | (16750) Error: Request failed with status code 422 at createError (/opt/iobroker/node_modules/axios/lib/core/createError.js:16:15) at settle (/opt/iobroker/node_modules/axios/lib/core/settle.j
tado.0 | 2021-04-15 21:42:13.589 | error | (16750) unhandled promise rejection: Request failed with status code 422
tado.0 | 2021-04-15 21:42:13.588 | error | (16750) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
tado.0 | 2021-04-15 21:42:13.472 | debug | (16750) Timeout set for timer '1533808' with 750ms
tado.0 | 2021-04-15 21:42:12.720 | info | (16750) Send API ZoneOverlay API call Home: 153380 zone : 8 config: {"setting":{"type":"HEATING","power":"ON","temperature":{"celsius":19}},"termination":{"typeSkillBasedApp":"NEXT_TIME_BLOCK","durati
tado.0 | 2021-04-15 21:42:12.720 | info | (16750) Temperature changed for room: 8 in home: 153380 to API with: 19
tado.0 | 2021-04-15 21:42:12.720 | debug | (16750) Device id channel : temperature
tado.0 | 2021-04-15 21:42:12.719 | debug | (16750) Device id channel : setting
tado.0 | 2021-04-15 21:42:12.719 | debug | (16750) Device id channel : 8
tado.0 | 2021-04-15 21:42:12.718 | debug | (16750) Device id channel : Rooms
tado.0 | 2021-04-15 21:42:12.718 | debug | (16750) Device id channel : 153380
tado.0 | 2021-04-15 21:42:12.717 | debug | (16750) Device id channel : 0
tado.0 | 2021-04-15 21:42:12.717 | debug | (16750) Device id channel : tado
tado.0 | 2021-04-15 21:42:12.714 | debug | (16750) Room mode set : NO_OVERLAY
tado.0 | 2021-04-15 21:42:12.713 | debug | (16750) Type set : HEATING
tado.0 | 2021-04-15 21:42:12.713 | debug | (16750) Room power set : ON
tado.0 | 2021-04-15 21:42:12.713 | debug | (16750) Room Temperature set: 19
tado.0 | 2021-04-15 21:42:12.712 | debug | (16750) DurationInSeconds set : 1800
tado.0 | 2021-04-15 21:42:12.712 | debug | (16750) FanSpeed set : COOL
tado.0 | 2021-04-15 21:42:12.712 | debug | (16750) Mode set : COOL

`

**Comment by seb2010** [comment]
another find:
devices channel for zones/rooms with multiple devices do not have a "devices" channel, but rather have the JSON-string as a string-value-state:
`[{"deviceType":"RU01","serialNo":"RU1553795xxx","shortSerialNo":"RU1553795xxx","currentFwVersion":"54.20","connectionState":{"value":true,"timestamp":"2021-04-15T20:07:44.473Z"},"characteristics":{"capabilities":["INSIDE_TEMPERATURE_MEASUREMENT","IDENTIFY"]},"batteryState":"NORMAL","duties":["ZONE_UI","CIRCUIT_DRIVER","ZONE_LEADER"]},{"deviceType":"VA02","serialNo":"VA2830045xxx","shortSerialNo":"VA2830045xxx","currentFwVersion":"79.1","connectionState":{"value":true,"timestamp":"2021-04-15T19:52:51.212Z"},"characteristics":{"capabilities":["INSIDE_TEMPERATURE_MEASUREMENT","IDENTIFY"]},"mountingState":{"value":"CALIBRATED","timestamp":"2021-02-11T22:42:41.050Z"},"batteryState":"NORMAL","childLockEnabled":false,"duties":["ZONE_UI","ZONE_DRIVER"]}]`

**Comment by seb2010** [comment]
I also can see the adapter write the states of the devices of room/zone 0 get overwritten with different values switching back and forth every time the update is running. If you can tell me how I can access the code of this experimental version here in github, I can help you debug, if you like.

**Comment by HGlab01** [comment]
First of all thanks for your support and the inputs!
Debug support is very welcome :-)
The commit belongs to
https://github.com/DrozmotiX/ioBroker.tado/tree/generic
The version uses an additional selfmade lib which writes a JSON to states. This one can be found here
https://github.com/HGlab01/ioBroker-jsonExplorer

I suggest to do it step-wise and to start with the room issue.
Can you provide a screenshot of the states so that it is easier to understand.
Additionally the result in the state
tado.X.YYYYY._info.JSON_response.Stage_09_ZoneStates_data_# where # is the number with the issue would be perfect.

The device issue is strange. The JSON is a array with two devices. This should be supported by the iobroker-jsonexplorer, but I have to check this.

But feel free to debug on your own and if you have any questions do not hesitate to ask. If you like we can schedule a discord session (#5336) for efficiency reasons ;-)

**Comment by HGlab01** [comment]
I tried your JSON and this worked fine. I got 2 devices. To be further investigated.
![image](https://user-images.githubusercontent.com/54232526/114937963-c8441c80-9e3e-11eb-97f9-9486567a0568.png)

**Comment by HGlab01** [comment]
For the device issue (just one JSON) I have an idea and to 99% a solution.

**Comment by seb2010** [comment]
then I will wait with further debuggin. I have to familiarize myserlf first with the process. My suspicion for the mixed up values in some zones I am suspecting that the DoZones and the underlying DoZoneStates functions are handling the indices of tha payload differently. Both request are handling Zone-data...

**Comment by HGlab01** [comment]
> My suspicion for the mixed up values in some zones I am suspecting that the DoZones and the underlying DoZoneStates functions are handling the indices of tha payload differently. Both request are handling Zone-data...

Yes, it sounds like this, but from code point of view this cannot happen :-)
I need your JSON and state view to understand whats going wrong...

Would be very nice to get following info from your installation:
1. Screenshot of all states to the zone/room where it does not work
2. Value in state tado.X.YYYYY.info.JSON_response.Stage_09_ZoneStates_data# where # is the number with the issue 
3. Value in state tado.X.YYYYY._info.JSON_response.Stage_08_ZonesData

For 2 and 3 you have to run the adapter in debug mode otherwise the state is empty

**Comment by seb2010** [comment]
Is there any way to send you the logs not here in this thread. I do not want to expose all my serial-numbers etc.

**Comment by seb2010** [comment]
I pinged you in discord

**Comment by HGlab01** [comment]
Feature can be tested in pre-release v0.3.0-0
Be aware that there are breaking changes in this version (check https://github.com/DrozmotiX/ioBroker.tado/blob/generic/README.md)!

Installation:
DrozmotiX/ioBroker.tado#v0.3.0-0

![image](https://user-images.githubusercontent.com/54232526/118825459-fd6ae100-b8ba-11eb-9e34-b9c46ce1ce5a.png)

**Comment by HGlab01** [comment]
update:
DrozmotiX/ioBroker.tado#v0.3.0-2

**Comment by seb2010** [comment]
I do see the .name object. Works as expected! Thank you very much!
