### ISSUE TITLE
Unhandled promise rejection

### ISSUE THREAD

**Issue by seb2010** [DrozmotiX/ioBroker.tado#341]
Hallo zusammen,

ich bekomme (ggf seit einiger Zeit) Warnungen von IOBroker zu restart-loops vom Tado-Adapter. Es ist immer derselbe Fehler:
2021-08-21 07:02:54.466  - [32minfo[39m: tado.0 (3233) Send API ZoneOverlay API call Home: 153xxx zone: 5 config: {"setting":{"type":"HEATING","power":"ON","temperature":{"celsius":27}},"termination":{"typeSkillBasedApp":"NEXT_TIME_BLOCK","durationInSeconds":null}}
2021-08-21 07:02:55.340  - [31merror[39m: tado.0 (3233) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
2021-08-21 07:02:55.341  - [31merror[39m: tado.0 (3233) unhandled promise rejection: Request failed with status code 422
2021-08-21 07:02:55.346  - [31merror[39m: tado.0 (3233) Error: Request failed with status code 422
    at createError (/opt/iobroker/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/opt/iobroker/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/opt/iobroker/node_modules/axios/lib/adapters/http.js:260:11)
    at IncomingMessage.emit (events.js:326:22)
    at IncomingMessage.EventEmitter.emit (domain.js:483:12)
    at endReadableNT (_stream_readable.js:1241:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
2021-08-21 07:02:55.347  - [31merror[39m: tado.0 (3233) Request failed with status code 422
2021-08-21 07:02:55.364  - [32minfo[39m: tado.0 (3233) cleaned everything up...
2021-08-21 07:02:55.364  - [32minfo[39m: tado.0 (3233) terminating
2021-08-21 07:02:55.365  - [33mwarn[39m: tado.0 (3233) Terminated (UNCAUGHT_EXCEPTION): Without reason

Habt ihr eine Ahnung was das sein könnte?

Grüße
SEB

**Comment by DutchmanNL** [comment]
Request failed with status code 422

The HyperText Transfer Protocol (HTTP) 422 Unprocessable Entity response status code indicates that the server understands the content type of the request entity, and the syntax of the request entity is correct, but it was unable to process the contained instructions.


 Basically just saying the Reques cannot been handled try again

**Comment by HGlab01** [comment]
@seb2010 please try a temperature less or equal 25 degree
Tado only supports a max of 25°
I will optimize the temperature validartion

**Comment by seb2010** [comment]
thanks @HGlab01, indeed I was using higher values than 25°!

**Comment by DutchmanNL** [comment]
> I will optimize the temperature validation

we should also add this as min/max value into the lib definitions, will not block scripts etc but at least in the admin this will prevent that error

**Comment by HGlab01** [comment]
> > I will optimize the temperature validation
> 
> we should also add this as min/max value into the lib definitions, will not block scripts etc but at least in the admin this will prevent that error

not so easy/possible, because different min/max for each device (heating, hotwater, aircondition)

**Comment by DutchmanNL** [comment]
> not so easy/possible, because different min/max for each device (heating, hotwater, aircondition)

would have been to easy :)

**Comment by HGlab01** [comment]
fixed in https://github.com/DrozmotiX/ioBroker.tado/commit/96dfce251d828b106ea5e99141f91a901e765349

**Comment by seb2010** [comment]
Hi guys. I do still get the error in version 0.3.7. But this time for 22°C:
<html>
<body>


tado.0 | 2021-09-03 18:04:06.881 | error | Request failed with status code 422
-- | -- | -- | --
tado.0 | 2021-09-03 18:04:06.880 | error | Error: Request failed with status code 422 at createError (/opt/iobroker/node_modules/axios/lib/core/createError.js:16:15) at settle (/opt/iobroker/node_modules/axios/lib/core/settle.js:17:12) at IncomingMessage.handleStreamEnd (/opt/iobroker/node_modules/axios/lib/adapters/http.js:260:11) at IncomingMessage.emit (events.js:326:22) at IncomingMessage.EventEmitter.emit (domain.js:483:12) at endReadableNT (_stream_readable.js:1241:12) at processTicksAndRejections (internal/process/task_queues.js:84:21)
tado.0 | 2021-09-03 18:04:06.874 | error | unhandled promise rejection: Request failed with status code 422
tado.0 | 2021-09-03 18:04:06.874 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
tado.0 | 2021-09-03 18:04:06.013 | info | Call API 'ZoneOverlay' for home '15xxxx' and zone '8' with body {"setting":{"type":"HEATING","power":"ON","temperature":{"celsius":22}},"termination":{"typeSkillBasedApp":"NEXT_TIME_BLOCK","durationInSeconds":null}}


</body>
</html>

Need to reopen or should I raise a new issue?

**Comment by HGlab01** [comment]
I am one week off. Afterwards I will check

**Comment by HGlab01** [comment]
Hi, I tried to reproduce but was not successful.
I have no idea why it is not working in your setup (and you are the first one who raised an issue for this).

My log:
```
2021-09-12 11:28:47.440 - debug: tado.0 (1132) GETS INTERESSTING!!!
2021-09-12 11:28:47.441 - debug: tado.0 (1132) Attribute 'tado.0.28yyyy.Rooms.1.setting.temperature.celsius' changed. 'celsius' will be checked.
2021-09-12 11:28:47.449 - debug: tado.0 (1132) Type is: HEATING
2021-09-12 11:28:47.450 - debug: tado.0 (1132) Power is: ON
2021-09-12 11:28:47.450 - debug: tado.0 (1132) Temperature is: 21
2021-09-12 11:28:47.450 - debug: tado.0 (1132) Execution mode (typeSkillBasedApp) is: NO_OVERLAY
2021-09-12 11:28:47.450 - debug: tado.0 (1132) DurationInSeconds is: 1800
2021-09-12 11:28:47.450 - debug: tado.0 (1132) Mode is: COOL
2021-09-12 11:28:47.450 - debug: tado.0 (1132) FanSpeed is: AUTO
2021-09-12 11:28:47.450 - info: tado.0 (1132) Temperature changed for room '1' in home '28yyyy' to '21'
2021-09-12 11:28:47.450 - info: tado.0 (1132) Call API 'ZoneOverlay' for home '28yyyy' and zone '1' with body {"setting":{"type":"HEATING","power":"ON","temperature":{"celsius":21}},"termination":{"typeSkillBasedApp":"NEXT_TIME_BLOCK","durationInSeconds":null}}
2021-09-12 11:28:48.201 - debug: tado.0 (1132) Timeout set for timer '28yyyy' with 750ms
2021-09-12 11:28:48.407 - debug: tado.0 (1132) API called with {"setting":{"type":"HEATING","power":"ON","temperature":{"celsius":21}},"termination":{"typeSkillBasedApp":"NEXT_TIME_BLOCK","durationInSeconds":null}}
2021-09-12 11:28:48.436 - debug: tado.0 (1132) state tado.0.28yyyy.Rooms.1.overlay.setting.power changed: ON (ack = true)
2021-09-12 11:28:48.437 - debug: tado.0 (1132) state tado.0.28yyyy.Rooms.1.overlay.setting.temperature.celsius changed: 21 (ack = true)
2021-09-12 11:28:48.441 - debug: tado.0 (1132) state tado.0.28yyyy.Rooms.1.overlay.termination.typeSkillBasedApp changed: NEXT_TIME_BLOCK (ack = true)
2021-09-12 11:28:48.442 - debug: tado.0 (1132) state tado.0.28yyyy.Rooms.1.overlay.termination.durationInSeconds changed: 1800 (ack = true)
2021-09-12 11:28:48.448 - debug: tado.0 (1132) state tado.0.28yyyy.Rooms.1.setting.power changed: ON (ack = true)
2021-09-12 11:28:48.450 - debug: tado.0 (1132) state tado.0.28yyyy.Rooms.1.setting.temperature.celsius changed: 21 (ack = true)
```

If I compare your and my API call it is equal.
my:
`Call API 'ZoneOverlay' for home '28yyyy' and zone '1' with body {"setting":{"type":"HEATING","power":"ON","temperature":{"celsius":21}},"termination":{"typeSkillBasedApp":"NEXT_TIME_BLOCK","durationInSeconds":null}}
`
your:
`Call API 'ZoneOverlay' for home '15xxxx' and zone '8' with body {"setting":{"type":"HEATING","power":"ON","temperature":{"celsius":21}},"termination":{"typeSkillBasedApp":"NEXT_TIME_BLOCK","durationInSeconds":null}}`

Maybe a reinstall helps. Or to change one time the Temp via Tado-App and then try again.
What I do not understand in your log:
The temp is changed twice!?"
The info "Temperature changed for room '8' in home '15xxxx' to '21'" appears at 2021-09-03 18:19:05.852 and 2021-09-03 18:19:05.652 (two times within 200ms). Are there any magic JavaScripts in place?

**Comment by DutchmanNL** [comment]
@HGlab01 the issue is an not handled async error of axios the api returns perfectly a 401 but the catch error is not handled 

unhandled promise rejection: Request failed with status code 422

**Comment by HGlab01** [comment]
@DutchmanNL right, this can be optimized, but is not the root cause, it is an optimization if the error happens.

**Comment by HGlab01** [comment]
@seb2010 please check https://github.com/DrozmotiX/ioBroker.tado/issues/341#issuecomment-917601351

**Comment by DutchmanNL** [comment]
> @DutchmanNL right, this can be optimized, but is not the root cause, it is an optimization if the error happens.

If the JSON is correctly submitted I assume just an API error, sometimes bits get lost 😂. Maybe a retry if it happens?

**Comment by seb2010** [comment]
Yes, there are very magical scripts active. But they are only modifying the temp over the adapter. So the tado-interaction is not that magical...
I changed the temps in all rooms through the app and restartet the adapter. It seems to be working now. I do not know what happened. Thanks for looking into it.

**Comment by DutchmanNL** [comment]
> Yes, there are very magical scripts active. But they are only modifying the temp over the adapter. So the tado-interaction is not that magical...
> I changed the temps in all rooms through the app and restartet the adapter. It seems to be working now. I do not know what happened. Thanks for looking into it.

are you changing the temperature by script in one go ? the could cause an API debounce when sending. to fast

**Comment by seb2010** [comment]
Hi Dutchman. The scripts do not by purpose change several temperatures at ones. This is more or less a reaction to changed values and subsequent rule-sets. But there is no coded prevention of potential high frequent adapter-interactions. So in general, this may reoccur.
I get your point and understand the consequence. My expectation though would be, that this API-friednly queueing is done internally by the adapter, as this is realy hard to hanlde in a script-scenario with a lot of "on(xyz)" subscriptions.

**Comment by DutchmanNL** [comment]
> I get your point and understand the consequence. My expectation though would be, that this API-friednly queueing is done internally by the adapter, as this is realy hard to hanlde in a script-scenario with a lot of "on(xyz)" subscriptions.

we should determine if that's the root cause, if yes a queuing or command delay makes sense in the adapter itself aggree

**Comment by seb2010** [comment]
Can I do something to pin-point it further?

**Comment by DutchmanNL** [comment]
> Can I do something to pin-point it further?

yea, reproduce a situation your scripts start to fire the tado adapter and monitor if the issue reoccurs :)

**Comment by HGlab01** [comment]
The queuing (waiting 750ms) of API Calls is implemented since half a year ;-)
https://github.com/DrozmotiX/ioBroker.tado/blob/954a5a4134d79eb7ebbf4299815a9bc76a07c9ba/main.js#L342

I tested if it works and it looks fine:
```
const setTemp = 'tado.0.[xxxxx].Rooms.1.setting.temperature.celsius';
setState(setTemp, 20);
setStateDelayed(setTemp, 21, 1000);
setStateDelayed(setTemp, 22, 1500); 
setStateDelayed(setTemp, 23, 2000);
setStateDelayed(setTemp, 24, 3000);
```
Log:
```
2021-09-14 18:30:40.571 - info: javascript.0 (1294) script.js.Tado: Temp. WZ von 24° auf 20° geändert
2021-09-14 18:30:40.575 - info: tado.0 (12706) Temperature changed for room '1' in home '283178' to '20'
2021-09-14 18:30:40.575 - info: tado.0 (12706) Call API 'ZoneOverlay' for home '283178' and zone '1' with body {"setting":{"type":"HEATING","power":"ON","temperature":{"celsius":20}},"termination":{"typeSkillBasedApp":"MANUAL","durationInSeconds":null}}
2021-09-14 18:30:43.569 - info: javascript.0 (1294) script.js.Tado: Temp. WZ von 20° auf 24° geändert
2021-09-14 18:30:43.578 - info: tado.0 (12706) Temperature changed for room '1' in home '283178' to '24'
2021-09-14 18:30:43.579 - info: tado.0 (12706) Call API 'ZoneOverlay' for home '283178' and zone '1' with body {"setting":{"type":"HEATING","power":"ON","temperature":{"celsius":24}},"termination":{"typeSkillBasedApp":"MANUAL","durationInSeconds":null}}
```

**Comment by seb2010** [comment]
I tried to provoke some errors here, but cannot reproduce it anymore. thank you guys

**Comment by HGlab01** [comment]
Thanks, so let's close it ;-)
